version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .  # Path to the Dockerfile
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      POSTGRES_DATABASE_URI: postgresql://fastapi_user:strongpassword123@db:5432/fastapi_db
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
