"""unique_id_generation

Revision ID: 4d7c0c9ff587
Revises: 0ec0e50ca16f
Create Date: 2025-01-03 18:48:05.764752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7c0c9ff587'
down_revision: Union[str, None] = '0ec0e50ca16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
